[package]
name = "sov-modules-api"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
sov-state = { path = "../sov-state", default-features = false }
sovereign-sdk = { path = "../../sdk" }
serde = { workspace = true }
borsh = { workspace = true }
thiserror = { workspace = true }
jmt = { workspace = true }
sha2 = { workspace = true }
bech32 = { workspace = true }
derive_more = { workspace = true }
#ed25519-dalek = {version =  "1", default-features = false}
ed25519-dalek = { version = "1" }
[features]
default = ["native"]
native = ["sov-state/native"]

