[package]
name = "demo-stf"
version = { workspace = true } 
edition = { workspace = true } 
resolver = "2"
authors = { workspace = true } 
homepage = "sovereign.xyz"
publish = false

[[bin]]
name = "bank-cmd"
path = "src/bank_cmd/main.rs"
required-features = ["native"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true}
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true }
clap = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["http-client", "server"], optional = true }
hex = { workspace = true }
tracing = { workspace = true }

sov-rollup-interface = { path = "../../rollup-interface" }
sov-election = { path = "../../module-system/module-implementations/examples/sov-election", default-features = false }
sov-sequencer-registry = { path = "../../module-system/module-implementations/sov-sequencer-registry", default-features = false }
sov-bank = { path = "../../module-system/module-implementations/sov-bank", default-features = false }
sov-modules-stf-template = { path = "../../module-system/sov-modules-stf-template" } # no features available
sov-value-setter = { path = "../../module-system/module-implementations/examples/sov-value-setter", default-features = false }
sov-accounts = { path = "../../module-system/module-implementations/sov-accounts", default-features = false }
sov-state = { path = "../../module-system/sov-state", default-features = false }
sov-modules-api = { path = "../../module-system/sov-modules-api", default-features = false }
sov-modules-macros = { path = "../../module-system/sov-modules-macros" }
# Only enable the db on "native" feature
sov-schema-db = { path = "../../full-node/db/sov-schema-db", features = ["temppath"], optional = true }
sov-db = { path = "../../full-node/db/sov-db", optional = true }

[dev-dependencies]
sov-rollup-interface = { path = "../../rollup-interface", features = ["mocks"] }
tempfile = "3.5.0"
rand = "0.8"

[features]
default = ["native"]
native = [
	"sov-state/temp",
	"dep:sov-db",
	"dep:sov-schema-db",
	"sov-bank/native",
	"sov-accounts/native",
	"sov-election/native",
	"sov-sequencer-registry/native",
	"sov-value-setter/native",
	"sov-modules-api/native",
	"sov-rollup-interface/mocks",
	"clap",
	"serde_json",
	"jsonrpsee",
	"toml"]
verifier = []
